
# Site settings
title: Musical Friends Kutzenhausen e. V.
email: info@musical-friends-kutzenhausen.de
description: > # this means to ignore newlines until "baseurl:"
  Musical Friends Kutzenhausen e. V.
baseurl: ""
url: "http://www.musical-friends-kutzenhausen.de"

# Build settings
markdown: kramdown

sources:
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets

gems: [jekyll-assets, font-awesome-sass, normalize-scss, jekyll-sitemap, 'jekyll-seo-tag']

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh

assets:
  digest: false

navigation:
  - title: Home
    url: /
  - title: Musicals
    url: /musicals.html
  - title: Spenden
    url: /spenden.html
  - title: Verein
    url: /verein.html
