
# Site settings
title: Musical Friends Kutzenhausen e. V.
email: info@musical-friends-kutzenhausen.de
description: > # this means to ignore newlines until "baseurl:"
  Musical Friends Kutzenhausen e. V.
baseurl: ""
url: "http://www.musical-friends-kutzenhausen.de"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true

sources:
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets

gems: [jekyll-assets, autoprefixer-rails, normalize-scss, jekyll-sitemap, jekyll-seo-tag]

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - process_images.sh

assets:
  digest: false
  autoprefixer:
    browsers:
      - "> 1%"
      - "IE >= 9"

navigation:
  - title: Home
    url: /index.html
  - title: Historie
    url: /historie.html
  - title: Verein
    url: /verein.html
  - title: Spenden
    url: /spenden.html

picture:
  source: "images/_originals"
  output: "images"
  markup: "picture"
  presets:
    hero:
      attr:
        class: "page__hero-image"
        itemprop: "image"
      ppi: [1]
      source_1600:
        media: "(min-width: 1600px)"
        width: "1600"
      source_1024:
        media: "(min-width: 1024px)"
        width: "1024"
      source_768:
        media: "(min-width: 768px)"
        width: "768"
      source_600:
        media: "(min-width: 600px)"
        width: "600"
      source_default:
        width: "320"
